package com.model;
// Generated 12 f�vr. 2023, 12:38:48 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "myregister")
public class Client implements java.io.Serializable {

	private Integer idClient;
	private int idAdmin;
	private String nomClient;
	private String prenom;
	private String contactClient;
	private String domicileClient;
	private String codeCni;

	public Client() {
	}

	public Client(int idAdmin) {
		this.idAdmin = idAdmin;
	}

	public Client(int idAdmin, String nomClient, String prenom, String contactClient, String domicileClient,
			String codeCni) {
		this.idAdmin = idAdmin;
		this.nomClient = nomClient;
		this.prenom = prenom;
		this.contactClient = contactClient;
		this.domicileClient = domicileClient;
		this.codeCni = codeCni;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_CLIENT", unique = true, nullable = false)
	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	@Column(name = "ID_ADMIN_", nullable = false)
	public int getIdAdmin() {
		return this.idAdmin;
	}

	public void setIdAdmin(int idAdmin) {
		this.idAdmin = idAdmin;
	}

	@Column(name = "NOM_CLIENT", length = 80)
	public String getNomClient() {
		return this.nomClient;
	}

	public void setNomClient(String nomClient) {
		this.nomClient = nomClient;
	}

	@Column(name = "PRENOM_", length = 90)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "CONTACT_CLIENT", length = 60)
	public String getContactClient() {
		return this.contactClient;
	}

	public void setContactClient(String contactClient) {
		this.contactClient = contactClient;
	}

	@Column(name = "DOMICILE_CLIENT", length = 90)
	public String getDomicileClient() {
		return this.domicileClient;
	}

	public void setDomicileClient(String domicileClient) {
		this.domicileClient = domicileClient;
	}

	@Column(name = "CODE_CNI", length = 80)
	public String getCodeCni() {
		return this.codeCni;
	}

	public void setCodeCni(String codeCni) {
		this.codeCni = codeCni;
	}

}
