package com.model;
// Generated 12 f�vr. 2023, 12:38:48 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", catalog = "myregister")
public class Facture implements java.io.Serializable {

	private Integer idFacture;
	private int idReservation;
	private Float amende;
	private Float montantAnvance;
	private Date dateAvance;
	private Date dateFinPaiement;
	private Float montatntAPayer;
	private String intituleAmende;
	private Date dateLivraison;
	private String lieuLivraison;
	private String livrer;
	private Float resteAPayer;
	private String retourner;
	private String etatMateriel;
	private Date dateRetour;

	public Facture() {
	}

	public Facture(int idReservation) {
		this.idReservation = idReservation;
	}

	public Facture(int idReservation, Float amende, Float montantAnvance, Date dateAvance, Date dateFinPaiement,
			Float montatntAPayer, String intituleAmende, Date dateLivraison, String lieuLivraison, String livrer,
			Float resteAPayer, String retourner, String etatMateriel, Date dateRetour) {
		this.idReservation = idReservation;
		this.amende = amende;
		this.montantAnvance = montantAnvance;
		this.dateAvance = dateAvance;
		this.dateFinPaiement = dateFinPaiement;
		this.montatntAPayer = montatntAPayer;
		this.intituleAmende = intituleAmende;
		this.dateLivraison = dateLivraison;
		this.lieuLivraison = lieuLivraison;
		this.livrer = livrer;
		this.resteAPayer = resteAPayer;
		this.retourner = retourner;
		this.etatMateriel = etatMateriel;
		this.dateRetour = dateRetour;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_FACTURE_", unique = true, nullable = false)
	public Integer getIdFacture() {
		return this.idFacture;
	}

	public void setIdFacture(Integer idFacture) {
		this.idFacture = idFacture;
	}

	@Column(name = "ID_RESERVATION", nullable = false)
	public int getIdReservation() {
		return this.idReservation;
	}

	public void setIdReservation(int idReservation) {
		this.idReservation = idReservation;
	}

	@Column(name = "AMENDE", precision = 8)
	public Float getAmende() {
		return this.amende;
	}

	public void setAmende(Float amende) {
		this.amende = amende;
	}

	@Column(name = "MONTANT_ANVANCE", precision = 8)
	public Float getMontantAnvance() {
		return this.montantAnvance;
	}

	public void setMontantAnvance(Float montantAnvance) {
		this.montantAnvance = montantAnvance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_AVANCE", length = 10)
	public Date getDateAvance() {
		return this.dateAvance;
	}

	public void setDateAvance(Date dateAvance) {
		this.dateAvance = dateAvance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FIN_PAIEMENT", length = 10)
	public Date getDateFinPaiement() {
		return this.dateFinPaiement;
	}

	public void setDateFinPaiement(Date dateFinPaiement) {
		this.dateFinPaiement = dateFinPaiement;
	}

	@Column(name = "MONTATNT_A_PAYER", precision = 8)
	public Float getMontatntAPayer() {
		return this.montatntAPayer;
	}

	public void setMontatntAPayer(Float montatntAPayer) {
		this.montatntAPayer = montatntAPayer;
	}

	@Column(name = "INTITULE_AMENDE", length = 100)
	public String getIntituleAmende() {
		return this.intituleAmende;
	}

	public void setIntituleAmende(String intituleAmende) {
		this.intituleAmende = intituleAmende;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_LIVRAISON", length = 10)
	public Date getDateLivraison() {
		return this.dateLivraison;
	}

	public void setDateLivraison(Date dateLivraison) {
		this.dateLivraison = dateLivraison;
	}

	@Column(name = "LIEU_LIVRAISON", length = 80)
	public String getLieuLivraison() {
		return this.lieuLivraison;
	}

	public void setLieuLivraison(String lieuLivraison) {
		this.lieuLivraison = lieuLivraison;
	}

	@Column(name = "LIVRER", length = 50)
	public String getLivrer() {
		return this.livrer;
	}

	public void setLivrer(String livrer) {
		this.livrer = livrer;
	}

	@Column(name = "RESTE_A_PAYER", precision = 8)
	public Float getResteAPayer() {
		return this.resteAPayer;
	}

	public void setResteAPayer(Float resteAPayer) {
		this.resteAPayer = resteAPayer;
	}

	@Column(name = "RETOURNER", length = 50)
	public String getRetourner() {
		return this.retourner;
	}

	public void setRetourner(String retourner) {
		this.retourner = retourner;
	}

	@Column(name = "ETAT_MATERIEL", length = 50)
	public String getEtatMateriel() {
		return this.etatMateriel;
	}

	public void setEtatMateriel(String etatMateriel) {
		this.etatMateriel = etatMateriel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_RETOUR", length = 19)
	public Date getDateRetour() {
		return this.dateRetour;
	}

	public void setDateRetour(Date dateRetour) {
		this.dateRetour = dateRetour;
	}

}
