package com.model;
// Generated 12 f�vr. 2023, 12:38:48 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Materiel generated by hbm2java
 */
@Entity
@Table(name = "materiel", catalog = "myregister")
public class Materiel implements java.io.Serializable {

	private Integer idMateriel;
	private String nomMateriel;
	private String descMateriel;
	private Float prix;
	private Integer quantite;

	public Materiel() {
	}

	public Materiel(Integer idMateriel, String nomMateriel, String descMateriel, Float prix, Integer quantite) {
		this.idMateriel = idMateriel;
		this.nomMateriel = nomMateriel;
		this.descMateriel = descMateriel;
		this.prix = prix;
		this.quantite = quantite;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_MATERIEL", unique = true, nullable = false)
	public Integer getIdMateriel() {
		return this.idMateriel;
	}

	public void setIdMateriel(Integer idMateriel) {
		this.idMateriel = idMateriel;
	}

	@Column(name = "NOM_MATERIEL", length = 100)
	public String getNomMateriel() {
		return this.nomMateriel;
	}

	public void setNomMateriel(String nomMateriel) {
		this.nomMateriel = nomMateriel;
	}

	@Column(name = "DESC_MATERIEL", length = 100)
	public String getDescMateriel() {
		return this.descMateriel;
	}

	public void setDescMateriel(String descMateriel) {
		this.descMateriel = descMateriel;
	}

	@Column(name = "PRIX", precision = 8)
	public Float getPrix() {
		return this.prix;
	}

	public void setPrix(Float prix) {
		this.prix = prix;
	}

	@Column(name = "QUANTITE")
	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

}
