package com.model;
// Generated 12 f�vr. 2023, 12:38:48 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "reservation", catalog = "myregister")
public class Reservation implements java.io.Serializable {

	private Integer idReservation;
	private int idClient;
	private Integer idMateriel;
	private Date dateDebutReservation;
	private Date dateFinReservation;
	private Integer quantiteReservee;

	public Reservation() {
	}

	public Reservation(int idClient) {
		this.idClient = idClient;
	}

	public Reservation(int idClient, Integer idMateriel, Date dateDebutReservation, Date dateFinReservation,
			Integer quantiteReservee) {
		this.idClient = idClient;
		this.idMateriel = idMateriel;
		this.dateDebutReservation = dateDebutReservation;
		this.dateFinReservation = dateFinReservation;
		this.quantiteReservee = quantiteReservee;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_RESERVATION", unique = true, nullable = false)
	public Integer getIdReservation() {
		return this.idReservation;
	}

	public void setIdReservation(Integer idReservation) {
		this.idReservation = idReservation;
	}

	@Column(name = "ID_CLIENT", nullable = false)
	public int getIdClient() {
		return this.idClient;
	}

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	@Column(name = "ID_MATERIEL")
	public Integer getIdMateriel() {
		return this.idMateriel;
	}

	public void setIdMateriel(Integer idMateriel) {
		this.idMateriel = idMateriel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEBUT_RESERVATION", length = 10)
	public Date getDateDebutReservation() {
		return this.dateDebutReservation;
	}

	public void setDateDebutReservation(Date dateDebutReservation) {
		this.dateDebutReservation = dateDebutReservation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FIN_RESERVATION", length = 10)
	public Date getDateFinReservation() {
		return this.dateFinReservation;
	}

	public void setDateFinReservation(Date dateFinReservation) {
		this.dateFinReservation = dateFinReservation;
	}

	@Column(name = "QUANTITE_RESERVEE")
	public Integer getQuantiteReservee() {
		return this.quantiteReservee;
	}

	public void setQuantiteReservee(Integer quantiteReservee) {
		this.quantiteReservee = quantiteReservee;
	}

}
